# Generated by Django 2.0.5 on 2018-05-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('street', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'addresses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=45, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=45, null=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.Address')),
            ],
            options={
                'db_table': 'debtors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Encumbrance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('encumbrance_kind', models.CharField(blank=True, max_length=45, null=True)),
                ('encumbrance_type', models.CharField(blank=True, max_length=45, null=True)),
                ('debt_amount', models.CharField(blank=True, max_length=45, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('debtor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.Debtor')),
            ],
            options={
                'db_table': 'encumbrances',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=45, null=True)),
                ('licensed', models.NullBooleanField(default=False)),
                ('license', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'notaries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prosecutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=45, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=45, null=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.Address')),
            ],
            options={
                'db_table': 'prosecutors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReasonDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notary_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.Notary')),
            ],
            options={
                'db_table': 'reason_documents',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='encumbrance',
            name='notary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.Notary'),
        ),
        migrations.AddField(
            model_name='encumbrance',
            name='object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.Object'),
        ),
        migrations.AddField(
            model_name='encumbrance',
            name='prosecutor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.Prosecutor'),
        ),
        migrations.AddField(
            model_name='encumbrance',
            name='reason_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.ReasonDocument'),
        ),
    ]
