# Generated by Django 2.0.5 on 2018-05-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='address_id',
            field=models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.DO_NOTHING, to='property.Address'),
        ),
        migrations.AlterField(
            model_name='encumbrance',
            name='debtor_id',
            field=models.ForeignKey(db_column='debtor_id', on_delete=django.db.models.deletion.DO_NOTHING, to='property.Debtor'),
        ),
        migrations.AlterField(
            model_name='encumbrance',
            name='notary_id',
            field=models.ForeignKey(db_column='notary_id', on_delete=django.db.models.deletion.DO_NOTHING, to='property.Notary'),
        ),
        migrations.AlterField(
            model_name='encumbrance',
            name='prosecutor_id',
            field=models.ForeignKey(db_column='prosecutor_id', on_delete=django.db.models.deletion.DO_NOTHING, to='property.Prosecutor'),
        ),
        migrations.AlterField(
            model_name='encumbrance',
            name='reason_document',
            field=models.ForeignKey(db_column='reason_document', on_delete=django.db.models.deletion.DO_NOTHING, to='property.ReasonDocument'),
        ),
        migrations.AlterField(
            model_name='prosecutor',
            name='address_id',
            field=models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.DO_NOTHING, to='property.Address'),
        ),
        migrations.AlterField(
            model_name='reasondocument',
            name='notary_id',
            field=models.ForeignKey(db_column='notary_id', on_delete=django.db.models.deletion.DO_NOTHING, to='property.Notary'),
        ),
    ]
