# Generated by Django 2.0.5 on 2018-05-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20180527_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encumbrance',
            name='object_id',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.DO_NOTHING, to='property.Object'),
        ),
    ]
