# Generated by Django 2.0.5 on 2018-05-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20180527_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasondocument',
            name='notary_id',
        ),
        migrations.AddField(
            model_name='encumbrance',
            name='hashcode',
            field=models.CharField(blank=True, default='secret', max_length=100, null=True),
        ),
    ]
