# Generated by Django 2.0.5 on 2018-05-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20180530_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='encumbrance',
            name='checked',
            field=models.NullBooleanField(default=False),
        ),
    ]
